CREATE DATABASE EMPRESA;
USE EMPRESA;

CREATE TABLE EMPLEADOS (
  DNI VARCHAR(9) NOT NULL ,
  NSS BIGINT(12) NOT NULL ,
  Nombre VARCHAR(20) NOT NULL ,
  Domicilio VARCHAR(60) ,
  Sexo ENUM('M','F') ,
  F_nac DATE ,
  Tipo ENUM( "Contables" , "Diseñadores" , "Desarrolladores" ),
  PRIMARY KEY(DNI)
);

CREATE TABLE DEPARTAMENTO (
  cod_Departamento VARCHAR(9) NOT NULL ,
  NUM_Empleados INT(8) NOT NULL ,
  Presupuesto FLOAT(20,3) NOT NULL ,
  PRIMARY KEY (cod_Departamento)
);

CREATE TABLE CENTROS_DE_ESTUDIOS (
  Cod_Centro VARCHAR(9) NOT NULL ,
  Nombre VARCHAR(100) NOT NULL ,
  Ciudad VARCHAR(50) NOT NULL ,
  PRIMARY KEY (Cod_Centro)
);

CREATE TABLE PUESTO_TRABAJO (
  Cod_puesto VARCHAR(9) NOT NULL ,
  Nombre_Trabajo VARCHAR(50) NOT NULL ,
  SalarioMinimo FLOAT(8,2) ,
  cod_Departamento VARCHAR(9) NOT NULL ,
  PRIMARY KEY (Cod_puesto)
);

CREATE TABLE TRABAJOS_EMPLEADOS (
  DNI VARCHAR(9) NOT NULL ,
  Cod_puesto VARCHAR(9) NOT NULL ,
  fecha_inicio DATE NOT NULL ,
  fecha_fin DATE ,
  PRIMARY KEY (DNI, Cod_puesto ,fecha_inicio)
);

CREATE TABLE ESTUDIOS_DE_EMPLEADOS (
  DNI VARCHAR(9) NOT NULL ,
  Cod_Centro VARCHAR(9) NOT NULL ,
  Cod_titulo VARCHAR(9) NOT NULL ,
  Especialidad VARCHAR(100),
  Año_finalizacion DATE NOT NULL ,
  PRIMARY KEY (DNI, Cod_Centro, Cod_titulo)
);

ALTER TABLE  PUESTO_TRABAJO ADD FOREIGN KEY (cod_Departamento) REFERENCES DEPARTAMENTO (cod_Departamento);
ALTER TABLE PUESTO_TRABAJO ADD CONSTRAINT fk_cod_Departamento FOREIGN KEY (cod_Departamento) REFERENCES DEPARTAMENTO (cod_Departamento);

ALTER TABLE  TRABAJOS_EMPLEADOS ADD FOREIGN KEY (Cod_puesto) REFERENCES PUESTO_TRABAJO (Cod_puesto);
ALTER TABLE TRABAJOS_EMPLEADOS ADD CONSTRAINT fk_cod_puesto FOREIGN KEY (Cod_puesto) REFERENCES PUESTO_TRABAJO (Cod_puesto);

ALTER TABLE  TRABAJOS_EMPLEADOS ADD FOREIGN KEY (DNI) REFERENCES EMPLEADOS (DNI);
ALTER TABLE TRABAJOS_EMPLEADOS ADD CONSTRAINT fk_DNI FOREIGN KEY (DNI) REFERENCES EMPLEADOS (DNI);

ALTER TABLE  ESTUDIOS_DE_EMPLEADOS ADD FOREIGN KEY (DNI) REFERENCES EMPLEADOS (DNI);
ALTER TABLE ESTUDIOS_DE_EMPLEADOS ADD CONSTRAINT fk_dni_ FOREIGN KEY (DNI) REFERENCES EMPLEADOS (DNI);

ALTER TABLE  ESTUDIOS_DE_EMPLEADOS ADD FOREIGN KEY (Cod_Centro) REFERENCES CENTROS_DE_ESTUDIOS (Cod_Centro);
ALTER TABLE ESTUDIOS_DE_EMPLEADOS ADD CONSTRAINT fk_cod_centro FOREIGN KEY (Cod_Centro) REFERENCES CENTROS_DE_ESTUDIOS (Cod_Centro);
